### ISSUE TITLE
mediawiki_api_call_helper example results in an error

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#136]
```
from wikibaseintegrator import wbi_core

query = {
    'action': 'query',
    'prop': 'revisions',
    'titles': 'Q2',
    'rvlimit': 10
}

print(wbi_core.FunctionsEngine.mediawiki_api_call_helper(query, allow_anonymous=True))
->
Traceback (most recent call last):
  File "/home/egil/src/python/descriptionbot/test.py", line 10, in <module>
    print(wbi_core.FunctionsEngine.mediawiki_api_call_helper(query, allow_anonymous=True))
  File "/usr/lib/python3.9/site-packages/wikibaseintegrator/wbi_core.py", line 1130, in mediawiki_api_call_helper
    return FunctionsEngine.mediawiki_api_call('POST', mediawiki_api_url, login_session, data=data, headers=headers, max_retries=max_retries,
  File "/usr/lib/python3.9/site-packages/wikibaseintegrator/wbi_core.py", line 965, in mediawiki_api_call
    json_data = response.json()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by dpriskorn** [comment]
```
In [1]: from wikibaseintegrator import wbi_core

In [2]: dir(wbi_core)
Out[2]: 
['BaseDataType',
 'CommonsMedia',
 'CorePropIntegrityException',
 'ExternalID',
 'FastRunContainer',
 'Form',
 'GeoShape',
 'GlobeCoordinate',
 'IDMissingError',
 'ItemEngine',
 'ItemID',
 'JsonParser',
 'Lexeme',
 'MWApiError',
 'ManualInterventionReqException',
 'Math',
 'MergeError',
 'MonolingualText',
 'MusicalNotation',
 'NonUniqueLabelDescriptionPairError',
 'Property',
 'Quantity',
 'SearchError',
 'Sense',
 'String',
 'TabularData',
 'Time',
 'Url',
 '__author__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__license__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'config',
 'copy',
 'datetime',
 'defaultdict',
 'json',
 'pandas',
 're',
 'requests',
 'time',
 'warn',
 'wbi_backoff']
```
Installed via pip: wikibaseintegrator  0.9.0

**Comment by dpriskorn** [comment]
Is there any reason to have the FunctionsEngine in core? WBI would probably get cleaner and faster if the auxiliary functions were moved to say wbi_functions

**Comment by dpriskorn** [comment]
I think it's missing an init, but I'm not very well versed in python classes yet.

**Comment by dpriskorn** [comment]
I upgraded to 0.10 and now it seems to work :)

**Comment by dpriskorn** [comment]
here is code that works with requests but NOT with WBI:
```
import requests
from wikibaseintegrator import wbi_core
from pprint import pprint

engine = wbi_core.FunctionsEngine()
    params = {
        'action': 'query',
        'list': 'search',
        'format': 'json',
        'utf8': '1',
        # All scientific articles without any description
        'srsearch': "haswbstatement:P31=Q13442814 -hasdescription:*",
    }
    pprint(params)
    data = requests.get(
        url="https://www.wikidata.org/w/api.php",
        params=params
    )
    pprint(data.json())
    data = engine.mediawiki_api_call(
        "GET",
        mediawiki_api_url="https://wikidata.org/w/api.php",
        data=params
    )
    pprint(data)

```

**Comment by LeMyst** [comment]
The issue with `FunctionsEngine.mediawiki_api_call_helper` come from the format of the response.
`FunctionsEngine.mediawiki_api_call` only accept json as format, so you need to add `'format': 'json'` to the params.

Like this

```python
from wikibaseintegrator import wbi_core

query = {
    'action': 'query',
    'prop': 'revisions',
    'titles': 'Q2',
    'rvlimit': 10,
    'format': 'json'
}

print(wbi_core.FunctionsEngine.mediawiki_api_call_helper(query, allow_anonymous=True))
```

It's already fixed on the GitHub repository/next version.

If there is no format, wbi force to json
If there is a format different than 'json', wbi raise en exception.
