### ISSUE TITLE
WBI is unable to set a description

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#138]
installed from pip v0.10

The correct API is wbsetdescription but I get an error suggesting that WBI use another API when setting a description:
```
Traceback (most recent call last):
  File "/home/egil/src/python/descriptionbot/descriptionbot/main.py", line 88, in <module>
    main()
  File "/home/egil/src/python/descriptionbot/descriptionbot/main.py", line 76, in main
    result = item.write(
  File "/usr/lib/python3.9/site-packages/wikibaseintegrator/wbi_core.py", line 632, in write
    json_data = FunctionsEngine.mediawiki_api_call_helper(data=payload, login=login, max_retries=max_retries, retry_after=retry_after,
  File "/usr/lib/python3.9/site-packages/wikibaseintegrator/wbi_core.py", line 1130, in mediawiki_api_call_helper
    return FunctionsEngine.mediawiki_api_call('POST', mediawiki_api_url, login_session, data=data, headers=headers, max_retries=max_retries,
  File "/usr/lib/python3.9/site-packages/wikibaseintegrator/wbi_core.py", line 996, in mediawiki_api_call
    raise MWApiError(response.json() if response else dict())
wikibaseintegrator.wbi_core.MWApiError: {'error': {'code': 'permissiondenied', 'info': 'You do not have the permissions needed to carry out this action.', 'messages': [{'name': 'wikibase-api-permissiondenied', 'parameters': [], 'html': {'*': 'You do not have the permissions needed to carry out this action.'}}, {'name': 'badaccess-groups', 'parameters': ['*', 1], 'html': {'*': 'Den åtgärd du har begärt kan enbart utföras av användare i gruppen: *.'}}], '*': 'See https://www.wikidata.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.'}, 'servedby': 'mw1342'}
```
The code I used was:
```
#!/usr/bin/env python3
# import warnings
# warnings.simplefilter(action='ignore', category=FutureWarning)
import gettext
import logging
from urllib.parse import quote

import requests
from wikibaseintegrator import wbi_core, wbi_login
from pprint import pprint

import config
# Import util first
# from modules import util
from modules import loglevel

# Settings
_ = gettext.gettext

#
# Functions
#
            
def main():
    logger = logging.getLogger(__name__)
    if config.loglevel is None:
        # Set loglevel
        loglevel.set_loglevel()
    logger.setLevel(config.loglevel)
    logger.level = logger.getEffectiveLevel()
    # file_handler = logging.FileHandler("europarl.log")
    # logger.addHandler(file_handler)

    engine = wbi_core.FunctionsEngine()
    params = {
        'action': 'query',
        'list': 'search',
        'format': 'json',
        'utf8': '1',
        # All scientific articles without any description
        'srsearch': "haswbstatement:P31=Q13442814 -hasdescription:*",
    }
    pprint(params)
    # data = engine.mediawiki_api_call(
    #     "GET",
    #     mediawiki_api_url="https://wikidata.org/w/api.php",
    #     data=params
    # )
    # pprint(data)
    data = requests.get(
        url="https://www.wikidata.org/w/api.php",
        params=params
    )
    # pprint(data.json())
    qids = [] # type: str
    for result in data.json()["query"]["search"]:
        qids.append(result["title"])
    pprint(qids)
    if len(qids) > 0:
        print("Logging in with Wikibase Integrator")
        config.login_instance = wbi_login.Login(
            user=config.username, pwd=config.password
        )
    count = 0
    for qid in qids:
        if count == 1:
            quit(0)
        item = wbi_core.ItemEngine(item_id=qid)
        print(type(item))
        item.set_description(
                "scientific article",
                lang="en",
                if_exists="KEEP"
        )
        print(type(item))
        result = item.write(
            config.login_instance,
            edit_summary=(
                "Added usage example " +
                "with [[Wikidata:Tools/DescriptionBot]]"
            )
        )
        print(result)
        print(f"{config.wd_prefix}{qid}")
        count += 1

if __name__ == "__main__":
    main()
```

**Comment by LeMyst** [comment]
Hello @dpriskorn 
I just tested to set description on test.wikidata.org with 0.10.0 (pypi version) and I got no issue with this code:

```python
import os
from pprint import pprint

from wikibaseintegrator import wbi_core, wbi_login
from wikibaseintegrator.wbi_config import config as wbi_config

wbi_config['MEDIAWIKI_API_URL'] = 'https://test.wikidata.org/w/api.php'
login = wbi_login.Login(user=os.getenv('WDUSER'), pwd=os.getenv('WDPASS'))
wd_item = wbi_core.ItemEngine(item_id='Q105081')

wd_item.set_description('test description', 'en', 'KEEP')

wd_item.write(login, edit_summary=("test test test"))
```

It seem you have a permission issue, can you give me the Entity you try to edit?
