### ISSUE TITLE
Error related to endpoint on dev2

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#218]
```
Traceback (most recent call last):
  File "C:/Users/E5450/PycharmProjects/ItemSubjector/main.py", line 8, in <module>
    from helpers.menus import select_task
  File "C:\Users\E5450\PycharmProjects\ItemSubjector\helpers\menus.py", line 19, in <module>
    from tasks import tasks
  File "C:\Users\E5450\PycharmProjects\ItemSubjector\tasks.py", line 46, in <module>
    scholarly_items.fetch_scientific_articles_without_main_subject()
  File "C:\Users\E5450\PycharmProjects\ItemSubjector\tasks.py", line 12, in fetch_scientific_articles_without_main_subject
    results = (execute_sparql_query(f'''
  File "C:\Users\E5450\PycharmProjects\ItemSubjector\venv\lib\site-packages\backoff\_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "C:\Users\E5450\PycharmProjects\ItemSubjector\venv\lib\site-packages\wikibaseintegrator\wbi_helpers.py", line 159, in execute_sparql_query
    if urlparse(endpoint).hostname.endswith(('wikidata.org', 'wikipedia.org', 'wikimedia.org')) and user_agent is None:
AttributeError: 'NoneType' object has no attribute 'endswith'
```
[the code is here](https://github.com/dpriskorn/ItemSubjector)

**Comment by LeMyst** [comment]
Fixed on master
