### ISSUE TITLE
Login error on dev3

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#222]
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.wikidata.org:443
⠧ Logging in with WikibaseIntegrator...DEBUG:urllib3.connectionpool:https://www.wikidata.org:443 "POST /w/api.php HTTP/1.1" 200 111
login_token:82ea3b687d20caf7fc8bd754ea22d6df613d3af3+\
⠦ Logging in with WikibaseIntegrator...DEBUG:urllib3.connectionpool:https://www.wikidata.org:443 "POST /w/api.php HTTP/1.1" 200 106
{'login': {'result': 'Failed', 'reason': 'Incorrect username or password entered. Please try again.'}}
Traceback (most recent call last):
  File "itemsubjector.py", line 128, in <module>
    main()
  File "itemsubjector.py", line 105, in main
    config.login_instance = wbi_login.Login(
  File "C:\Users\E5450\PycharmProjects\ItemSubjector\venv\lib\site-packages\backoff\_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "C:\Users\E5450\PycharmProjects\ItemSubjector\venv\lib\site-packages\wikibaseintegrator\wbi_login.py", line 129, in __init__
    raise LoginError("Login failed. Reason: '{}'".format(login_result['login']['reason']))
wikibaseintegrator.wbi_login.LoginError: Login failed. Reason: 'Incorrect username or password entered. Please try again.'
```
code invoking login is here: https://github.com/dpriskorn/ItemSubjector/blob/1ceea35d97051717223005cfd10ff4dcbd948dfe/itemsubjector.py#L105
the username and password is exactly the same as in v0.11 used in other projects with no problems so I'm guessing something is wrong in dev3 but when I read the code it looked fine.

**Comment by dpriskorn** [comment]
It was a bug on my part with having 2 variables in my config.py with "username" and the last containing "User:So9q" for inclusion in the user-agent string.
