### ISSUE TITLE
MWApiError related to permission on v0.12

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#224]
```
Error while writing to the Wikibase instance
Traceback (most recent call last):
  File "itemsubjector.py", line 140, in <module>
    main()
  File "itemsubjector.py", line 135, in main
    process_results(results)
  File "itemsubjector.py", line 89, in process_results
    item.upload_one_statement_to_wikidata(
  File "C:\Users\E5450\PycharmProjects\ItemSubjector\models\wikidata.py", line 226, in upload_one_statement_to_wikidata
    result = wbi.item.write(
  File "C:\Users\E5450\PycharmProjects\ItemSubjector\venv\lib\site-packages\wikibaseintegrator\entities\item.py", line 76, in write
    json_data = super(Item, self)._write(data=self.get_json(), **kwargs)
  File "C:\Users\E5450\PycharmProjects\ItemSubjector\venv\lib\site-packages\wikibaseintegrator\entities\baseentity.py", line 142, in _write
    json_data = mediawiki_api_call_helper(data=payload, login=self.api.login, allow_anonymous=allow_anonymous, is_bot=self.api.is_bot, **kwargs)
  File "C:\Users\E5450\PycharmProjects\ItemSubjector\venv\lib\site-packages\wikibaseintegrator\wbi_helpers.py", line 156, in mediawiki_api_call_helper
    return mediawiki_api_call('POST', mediawiki_api_url=mediawiki_api_url, session=login_session, data=data, headers=headers, max_retries=max_retries,
  File "C:\Users\E5450\PycharmProjects\ItemSubjector\venv\lib\site-packages\wikibaseintegrator\wbi_helpers.py", line 99, in mediawiki_api_call
    raise MWApiError(response.json() if response else {})
wikibaseintegrator.wbi_exceptions.MWApiError: {'error': {'code': 'permissiondenied', 'info': 'You do not have the permissions needed to carry out this action.', 'messages': [{'n
ame': 'wikibase-api-permissiondenied', 'parameters': [], 'html': {'*': 'You do not have the permissions needed to carry out this action.'}}, {'name': 'nocreate-loggedin', 'param
eters': [], 'html': {'*': 'Du har inte behörighet att skapa nya sidor.'}}, {'name': 'badaccess-groups', 'parameters': ['*, [[Wikidata:Users|Användare]]', 2], 'html': {'*': 'Den
åtgärd du har begärt kan enbart utföras av användare i en av grupperna: *, <a href="/wiki/Wikidata:Users" title="Wikidata:Users">Användare</a>.'}}], '*': 'See https://www.wikida
ta.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.or
g/&gt; for notice of API deprecations and breaking changes.'}, 'servedby': 'mw2396'}
```
code is here: https://github.com/dpriskorn/ItemSubjector

I'm using a botpassword with limited permissions (no create permission it seems)
It looks like wbi is trying to create a new item? I might be using the wrong syntax.

**Comment by dpriskorn** [comment]
Bug in my syntax. Fixed. First successful edit with v0.12 🎉: 
https://www.wikidata.org/w/index.php?title=Q37263894&type=revision&diff=1496540519&oldid=1419173536
