### ISSUE TITLE
RC1: Uploading to test.wikidata does not work

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#292]
Traceback (most recent call last):
  File "C:/Users/E5450/PycharmProjects/OpenAlexBot/swepub.py", line 4, in <module>
    oa.start()
  File "C:\Users\E5450\PycharmProjects\OpenAlexBot\openalexbot\__init__.py", line 370, in start
    self.__process_dois__()
  File "C:\Users\E5450\PycharmProjects\OpenAlexBot\openalexbot\__init__.py", line 337, in __process_dois__
    self.__import_new_item__(doi=doi, work=work, wbi=wbi)
  File "C:\Users\E5450\PycharmProjects\OpenAlexBot\openalexbot\__init__.py", line 103, in __import_new_item__
Error while writing to the Wikibase instance
    self.__upload_new_item__(item=self.__prepare_new_item__(doi=doi, work=work, wbi=wbi))
  File "C:\Users\E5450\PycharmProjects\OpenAlexBot\openalexbot\__init__.py", line 356, in __upload_new_item__
    new_item = item.write(summary="New item imported from OpenAlex")
  File "C:\Users\E5450\PycharmProjects\OpenAlexBot\venv\lib\site-packages\wikibaseintegrator\entities\item.py", line 88, in write
    json_data = super()._write(data=self.get_json(), **kwargs)
  File "C:\Users\E5450\PycharmProjects\OpenAlexBot\venv\lib\site-packages\wikibaseintegrator\entities\baseentity.py", line 154, in _write
    json_result: dict = mediawiki_api_call_helper(data=payload, login=self.api.login, allow_anonymous=allow_anonymous, is_bot=self.api.is_bot, **kwargs)
  File "C:\Users\E5450\PycharmProjects\OpenAlexBot\venv\lib\site-packages\wikibaseintegrator\wbi_helpers.py", line 187, in mediawiki_api_call_helper
    return mediawiki_api_call('POST', mediawiki_api_url=mediawiki_api_url, session=login_session, data=data, headers=headers, max_retries=max_retries,
  File "C:\Users\E5450\PycharmProjects\OpenAlexBot\venv\lib\site-packages\wikibaseintegrator\wbi_helpers.py", line 112, in mediawiki_api_call
    raise MWApiError(response.json() if response else {})
wikibaseintegrator.wbi_exceptions.MWApiError: {'error': {'code': 'modification-failed', 'info': 'Bad value type wikibase-entityid, expected string', 'messages': [{'name': 'wikibase-validator-bad-value-type', 'parameters': ['wikibase-entityid', 'string'], 'html': {'*': 'Bad value type wikibase-entityid, expected string'}}], '*': 'See https://test.wikidata.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes.'}, 'servedby': 'mw1406'}

used the following config
```
config: Dict[str, Union[str, int, None, bool]] = {
    'BACKOFF_MAX_TRIES': 5,
    'BACKOFF_MAX_VALUE': 3600,
    'USER_AGENT': None,
    'PROPERTY_CONSTRAINT_PID': 'P2302',
    'DISTINCT_VALUES_CONSTRAINT_QID': 'Q21502410',
    'COORDINATE_GLOBE_QID': 'http://www.wikidata.org/entity/Q2',
    'CALENDAR_MODEL_QID': 'http://www.wikidata.org/entity/Q1985727',
    'MEDIAWIKI_API_URL': 'https://test.wikidata.org/w/api.php',
    'MEDIAWIKI_INDEX_URL': 'https://www.wikidata.org/w/index.php',
    'MEDIAWIKI_REST_URL': 'https://test.wikidata.org/w/rest.php',
    'SPARQL_ENDPOINT_URL': 'https://query.wikidata.org/sparql',
    'WIKIBASE_URL': 'http://test.wikidata.org',
    'DEFAULT_LANGUAGE': 'en',
    'DEFAULT_LEXEME_LANGUAGE': 'Q1860'
}
```

**Comment by dpriskorn** [comment]
could be because I only changed some of the values to "test"
I think WBI should support both www.wikidata and test.wikidata out of the box. Make it easy for the user to change between them.

**Comment by dpriskorn** [comment]
I tried changing more variable but got the same error
![bild](https://user-images.githubusercontent.com/68460690/154037040-84887746-720d-43b4-a7ca-028084d9118d.png)

config: Dict[str, Union[str, int, None, bool]] = {
    'BACKOFF_MAX_TRIES': 5,
    'BACKOFF_MAX_VALUE': 3600,
    'USER_AGENT': None,
    'PROPERTY_CONSTRAINT_PID': 'P2302',
    'DISTINCT_VALUES_CONSTRAINT_QID': 'Q21502410',
    'COORDINATE_GLOBE_QID': 'http://test.wikidata.org/entity/Q2',
    'CALENDAR_MODEL_QID': 'http://test.wikidata.org/entity/Q1985727',
    'MEDIAWIKI_API_URL': 'https://test.wikidata.org/w/api.php',
    'MEDIAWIKI_INDEX_URL': 'https://test.wikidata.org/w/index.php',
    'MEDIAWIKI_REST_URL': 'https://test.wikidata.org/w/rest.php',
    'SPARQL_ENDPOINT_URL': 'https://query.wikidata.org/sparql',
    'WIKIBASE_URL': 'http://test.wikidata.org',
    'DEFAULT_LANGUAGE': 'en',
    'DEFAULT_LEXEME_LANGUAGE': 'Q1860'
}

**Comment by LeMyst** [comment]
When I want to test something on test.wikidata.org, I simply use
```
from wikibaseintegrator.wbi_config import config as wbi_config
wbi_config['MEDIAWIKI_API_URL'] = 'https://test.wikidata.org/w/api.php'
wbi_config['MEDIAWIKI_INDEX_URL'] = 'https://test.wikidata.org/w/index.php'  # If you need OAuth1
wbi_config['MEDIAWIKI_REST_URL'] = 'https://test.wikidata.org/w/rest.php'  # If you need OAuth2

login_instance = wbi_login.Login(user=WDUSER, password=WDPASS)
wbi = WikibaseIntegrator(login=login_instance)
item = wbi.item.get('Q42544')  # Q952168
```

**Comment by dpriskorn** [comment]
> Can you share how you build your Item object ?

yes, I used a series of private methods. Here is the class with the methods involved the whole class is here https://github.com/dpriskorn/OpenAlexBot/blob/master/openalexbot/__init__.py:
```
class OpenAlexBot(BaseModel):
    """
    This class takes a CSV as input
    The column "query_string" is then processed row by row
    It supports both "naked" dois and with prefix.
    """
    dataframe: Optional[DataFrame]
    dois: Optional[Set[str]]
    email: Optional[str]
    filename: str
    doi_series: Optional[Series]

    def __import_new_item__(
            self, doi: str, work: Work, wbi: WikibaseIntegrator
    ):
        if (doi, work, wbi) is None:
            raise ValueError("Did not get what we need")
        self.__upload_new_item__(item=self.__prepare_new_item__(doi=doi, work=work, wbi=wbi))

    def __prepare_cites_works__(self, work: Work, reference: List[Claim]):
        if (work, reference) is None:
            raise ValueError("did not get what we need")
        logger.info("Preparing cites works claims")
        oa = OpenAlex(email=self.email)
        cites_works: List[datatypes.Item] = []
        for referenced_work_url in work.referenced_works:
            referenced_work = oa.get_single_work(referenced_work_url)
            # print(referenced_work.dict())
            doi = referenced_work.ids.doi_id
            if doi is not None:
                if self.__found_using_cirrussearch__(doi):
                    qid = self.__get_first_qid_from_cirrussearch__(doi)
                    logger.info(f"qid found for this reference: {qid}")
                    # exit()
                    cites_work = datatypes.Item(
                        prop_nr=Property.CITES_WORK.value,
                        value=qid,
                        references=[reference]
                    )
                    cites_works.append(
                        cites_work
                    )
                else:
                    # TODO decide whether to import transitive references also
                    logger.warning(f"Reference DOI '{doi}' not found in Wikidata")
            else:
                # TODO decide whether to import these
                logger.warning(f"DOI was None for OpenAlex ID {referenced_work_url} "
                               f"with ids {referenced_work.ids}, skipping")
        logger.debug(f"Generated {len(cites_works)} cited works")
        # if config.loglevel == logging.DEBUG:
        #     print(cites_works)
        return cites_works

    @staticmethod
    def __prepare_reference_claim__(id: str = None, work: Work = None) -> List[Claim]:
        if work is None:
            raise ValueError("did not get what we need")
        logger.info("Preparing reference claim")
        # Prepare reference
        if id is not None:
            id_without_prefix = URL(id).path_segment(0)
            logger.info(f"Using OpenAlex id: {id_without_prefix} extracted from {id}")
            openalex_id = datatypes.ExternalID(
                prop_nr=Property.OPENALEX_ID.value,
                value=id_without_prefix
            )
        else:
            # Fallback to the work id as id
            logger.info(f"Using OpenAlex id: {work.id_without_prefix}")
            openalex_id = datatypes.ExternalID(
                prop_nr=Property.OPENALEX_ID.value,
                value=work.id_without_prefix
            )
        retrieved_date = datatypes.Time(
            prop_nr="P813",  # Fetched today
            time=datetime.utcnow().replace(
                tzinfo=timezone.utc
            ).replace(
                hour=0,
                minute=0,
                second=0,
            ).strftime("+%Y-%m-%dT%H:%M:%SZ")
        )
        stated_in = datatypes.Item(
            prop_nr="P248",
            value=StatedIn.OPENALEX.value
        )
        claims = []
        for claim in (retrieved_date, stated_in, openalex_id):
            if claim is not None:
                claims.append(claim)
        return claims

    def __prepare_authors__(self, work: Work) -> Optional[List[Claim]]:
        """
        This method prepares the author claims.
        Unfortunately OpenAlex neither has numerical positions on authors
        nor first and last names separation.
        Neither Crossref nor OpenAlex has numerical ordinals.
        We copy the current praxis at WD and assign numerals trusting the order of OpenAlex
        """
        if work is None:
            raise ValueError("did not get what we need")
        logger.info("Preparing author claims")
        authors = []
        logger.info(f"Found {len(work.authorships)} authorships to process")
        ordinal = 1
        for authorship in work.authorships:
            if authorship.author.orcid is not None:
                id = authorship.author.id
                name = authorship.author.display_name
                orcid = authorship.author.orcid_id
                # The positions are one of (first, middle, last)
                position = authorship.author_position
                # We ignore authorship.institutions for now
                logger.info(f"Found author with name '{name}', position {position}, orcid {orcid} and id '{id}'")
                series_ordinal = datatypes.String(
                    prop_nr=Property.SERIES_ORDINAL.value,
                    value=str(ordinal)
                )
                qid = self.__get_first_qid_from_cirrussearch__(query_string=orcid)
                if qid:
                    author = datatypes.Item(
                        prop_nr=Property.AUTHOR.value,
                        value=qid,
                        qualifiers=[series_ordinal],
                        references=[self.__prepare_reference_claim__(id=id, work=work)]
                    )
                else:
                    author = datatypes.String(
                        prop_nr=Property.AUTHOR_NAME_STRING.value,
                        value=name,
                        qualifiers=[series_ordinal],
                        references=[self.__prepare_reference_claim__(id=id, work=work)]
                    )
                authors.append(author)
                ordinal += 1
        return authors

    def __prepare_subjects__(self, work: Work) -> Optional[List[Claim]]:
        """This method prepares the concept aka main subject claims."""
        if work is None:
            raise ValueError("did not get what we need")
        logger.info("Preparing subject claims")
        subjects = []
        for concept in work.concepts:
            if concept.wikidata_id is not None:
                qid = concept.wikidata_id
                label = concept.display_name
                id = concept.id
                logger.info(f"Found concept with name '{label}' and wikidata id '{qid}'")
                subject = datatypes.Item(
                    prop_nr=Property.MAIN_SUBJECT.value,
                    value=qid,
                    references=[self.__prepare_reference_claim__(id=id, work=work)]
                )
                subjects.append(subject)
        return subjects

    def __prepare_other_claims__(self, doi: str, work: Work, reference: List[Claim]):
        if (work, doi, reference) is None:
            raise ValueError("did not get what we need")
        logger.info("Preparing other claims")
        title = datatypes.MonolingualText(
            prop_nr=Property.TITLE.value,
            text=work.title,
            language="en",
            references=[reference]
        )
        doi = datatypes.ExternalID(
            prop_nr=Property.DOI.value,
            value=doi.lower(),  # This is a community norm in Wikidata
            references=[reference]
        )
        type_qid = WorkTypeToQid(work=work)
        type_qid = type_qid.get_qid()
        instance_of = datatypes.Item(
            prop_nr=Property.INSTANCE_OF.value,
            value=type_qid,
            references=[reference]
        )
        publication_date = datatypes.Time(
            prop_nr=Property.PUBLICATION_DATE.value,
            time=datetime.strptime(work.publication_date, "%Y-%m-%d").strftime("+%Y-%m-%dT%H:%M:%SZ")
        )
        self.__prepare_authors__(work=work)
        if work.biblio.issue is not None:
            issue = datatypes.String(
                prop_nr=Property.ISSUE.value,
                value=work.biblio.issue
            )
        else:
            issue = None
        list_of_claims = []
        for claim in (doi, instance_of, title, publication_date, issue):
            if claim is not None:
                list_of_claims.append(claim)
        if len(list_of_claims) > 0:
            return list_of_claims
        else:
            return None

    def __prepare_new_item__(
            self, doi: str, work: Work, wbi: WikibaseIntegrator
    ) -> entities.Item:
        """This method converts OpenAlex data into a new Wikidata item"""
        if (doi, work, wbi) is None:
            raise ValueError("Did not get what we need")
        # TODO language of display name using langdetect and set dynamically
        detected_language = langdetect.detect(work.display_name)
        logger.info(f"Detected language {detected_language} for '{work.display_name}'")
        item = wbi.item.new()
        item.labels.set(detected_language, work.display_name)
        item.descriptions.set("en", f"scientific article from {work.publication_year}")
        # Prepare claims
        # First prepare the reference needed in other claims
        reference = self.__prepare_reference_claim__(work=work)
        authors = self.__prepare_authors__(work=work)
        cites_works = self.__prepare_cites_works__(work=work, reference=reference)
        subjects = self.__prepare_subjects__(work=work)
        if len(subjects) > 0:
            item.add_claims(subjects)
        if len(authors) > 0:
            item.add_claims(authors)
        if len(cites_works) > 0:
            item.add_claims(cites_works)
        # TODO convert more data from OpenAlex work to claims
        item.add_claims(
            self.__prepare_other_claims__(doi=doi, work=work, reference=reference),
        )
        if config.loglevel == logging.DEBUG:
            logger.debug("Printing the item json")
            print(item.get_json())
        return item

    def __upload_new_item__(self, item: entities.Item):
        if item is None:
            raise ValueError("Did not get what we need")
        if config.upload_enabled:
            new_item = item.write(summary="New item imported from OpenAlex")
            print(f"Added new item {self.entity_url(new_item.id)}")
            if config.press_enter_to_continue:
                input("press enter to continue")
        else:
            print("skipped upload")
```

**Comment by LeMyst** [comment]
I feel like something is missing (either 'id' or 'new' field) in this error and #294

**Comment by LeMyst** [comment]
Can you print the json by adding `print(item.get_json())` before `new_item = item.write(summary="New item imported from OpenAlex")`
Thanks
