### ISSUE TITLE
Problems with Form datatype

### ISSUE THREAD

**Issue by LizzAlice** [LeMyst/WikibaseIntegrator#498]
I am trying to import an entity from wikidata into my local instance which has the datatype form. 
This is done with the following code:

``` 
from wikibaseintegrator.models.claims import Claims
entity = self.wikibase_integrator.property.get(entity_id="P5830")
entity.claims = Claims()
local_id = entity.write(login=login, as_new=True).id
```

However, this throws the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/wikibaseintegrator/entities/baseentity.py", line 237, in _write
    json_result: dict = edit_entity(data=data, id=entity_id, type=self.type, summary=summary, clear=clear, is_bot=is_bot, allow_anonymous=allow_anonymous,
  File "/usr/local/lib/python3.9/dist-packages/wikibaseintegrator/wbi_helpers.py", line 332, in edit_entity
    return mediawiki_api_call_helper(data=params, is_bot=is_bot, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/wikibaseintegrator/wbi_helpers.py", line 214, in mediawiki_api_call_helper
    return mediawiki_api_call('POST', mediawiki_api_url=mediawiki_api_url, session=session, data=data, headers=headers, max_retries=max_retries, retry_after=retry_after, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/wikibaseintegrator/wbi_helpers.py", line 127, in mediawiki_api_call
    raise MWApiError(json_data['error'])
wikibaseintegrator.wbi_exceptions.MWApiError: 'A datatype was expected, but either missing or not recognized.'
'A datatype was expected, but either missing or not recognized.'
```
So, I printed the entity in question, expecting the datatype to be missing somehow:
```
<PropertyEntity @892040 _BaseEntity__api=<wikibaseintegrator.wikibaseintegrator.WikibaseIntegrator object at 0x7fbf0a75e9d0>
         _BaseEntity__title='Property:P5830'
         _BaseEntity__pageid=56550935
         _BaseEntity__lastrevid=1785806292
         _BaseEntity__type='property'
         _BaseEntity__id='P5830'
         _BaseEntity__claims=<Claims @75ffa0 _Claims__claims={}>
         _PropertyEntity__datatype=<WikibaseDatatype.FORM: 'wikibase-form'>
         _PropertyEntity__labels=<Labels @892c70 _LanguageValues__values={'en': <LanguageValue @750280 _LanguageValue__language='en' _LanguageValue__value='subject form' _LanguageValue__removed=False>, 'de': <LanguageValue @753a60 _LanguageValue__language='de' _LanguageValue__value='demonstriert Form' _LanguageValue__removed=False>}>
         _PropertyEntity__descriptions=<Descriptions @75e400 _LanguageValues__values={'en': <LanguageValue @75f460 _LanguageValue__language='en' _LanguageValue__value="(qualifier) statement applies only to listed forms of statement's subject" _LanguageValue__removed=False>, 'de': <LanguageValue @75f520 _LanguageValue__language='de' _LanguageValue__value='(Qualifikator) die Form eines Lexems, welche durch ein Verwendungsbeispiel demonstriert wird' _LanguageValue__removed=False>}>
         _PropertyEntity__aliases=<Aliases @8c19a0 _Aliases__aliases={'en': [<Alias @74e220 _LanguageValue__language='en' _LanguageValue__value='form demonstrated' _LanguageValue__removed=False>, <Alias @74e280 _LanguageValue__language='en' _LanguageValue__value='demonstrates form' _LanguageValue__removed=False>, <Alias @74e2e0 _LanguageValue__language='en' _LanguageValue__value='applies to form' _LanguageValue__removed=False>]}>>
```

However, as you can see, there is a datatype. To be sure, I also printed `entity.datatype`, which came back as `WikibaseDatatype.FORM`. Could it be that there is a problem with that datatype?

**Comment by LizzAlice** [comment]
I had not installed it, with the extension it works. Thank you!

**Comment by LeMyst** [comment]
Nice!
Maybe I should move Lexeme data type to the extra folder?
