### ISSUE TITLE
Invalid CSRF token when using bot password

### ISSUE THREAD

**Issue by LeMyst** [LeMyst/WikibaseIntegrator#89]
```
Error while writing to the Wikibase instance
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    wd_item.write(login_instance)
  File "/home/user/WikibaseIntegrator/wikibaseintegrator/wbi_core.py", line 673, in write
    raise MWApiError(json_data)
wikibaseintegrator.wbi_core.MWApiError: {'error': {'code': 'badtoken', 'info': 'Invalid CSRF token.', '*': 'See https://www.wikidata.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.'}, 'servedby': 'mw1377'}
```

**Comment by LeMyst** [comment]
* Maybe add a warning if someone try to use a Login object initialized to another mediawiki.
* Add more documentation in the README.md to show how to configure correctly when not using Wikidata.
